M48
; DRILL file {KiCad (6.0.4-0)} date Tuesday, May 03, 2022 at 08:05:31 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-03T20:05:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0935
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X6.74Y-2.685
X6.78Y-2.485
X6.82Y-2.685
T2
X4.1223Y-3.4284
X4.1223Y-3.6016
T3
X6.68Y-2.485
X6.68Y-2.61
X6.88Y-2.485
X6.88Y-2.61
T4
X4.03Y-2.425
X4.03Y-5.12
X7.85Y-2.425
X7.85Y-5.12
T0
M30
